### ISSUE TITLE
The input size  problem

### ISSUE THREAD

**Issue by water-wave** [fudan-zvg/SETR#15]
Thank you for your great work.The size of my picture is (256,832),how should I deal with it?Please tell me more details.thanks.

**Comment by cgn2000** [comment]
出现了这样一个错误，KeyError: 'VisionTransformer is not in the backbone registry'，请问有解决方法吗？
或者训练自己的数据集的教程能不能再完善一点，谢谢

**Comment by sixiaozheng** [comment]
1. you will have to organize your dataset to meet the requirements of mmsegmentation. Please check https://mmsegmentation.readthedocs.io/en/latest/tutorials/customize_datasets.html. 

2. Please refer to SETR/mmseg/datasets/ade.py to write a python script SETR/mmseg/datasets/{your_dataset}.py for your own dataset, and add your dataset into SETR/mmseg/datasets/__init__.py. 

3. Please refer to SETR/configs/_base_/datasets/ade20k.py to write a configuration file for your own dataset, SETR/configs/_base_/datasets/{your_dataset}.py. You need to modify dataset_type, data_root, img_scale, crop_size, samples_per_gpu, img_dir, ann_dir, split. 

Note that the h and w of crop_size should be equal and must be in multiplies of 16. Neither of h and w is allowed to exceed the shortest side of the image after random resize — dict(type='Resize', img_scale=img_scale, ratio_range=(0.5, 2.0))

**Comment by water-wave** [comment]
Thank you for your reply.I will follow steps that your give.thanks  again.
