### ISSUE TITLE
About the position embeddings for patches

### ISSUE THREAD

**Issue by 2iyuye** [fudan-zvg/SETR#2]
Since the patches come from a 2D images, the position information consists of two directions, in other words, x-axis and y-axis indexes. This is different from the case in 1-D sequence. How do you implement the position embedding? Can you share the details since the code is not released?

**Comment by lzrobots** [comment]
We first flatten the patching embedding to a 1D sequence. To encode the patch spacial information, we learn a specific position embedding for every location which is then added to patch embedding to form the final 1D sequence input.

**Comment by 2iyuye** [comment]
I am just wondering whether your position embedding is learnt by network, or using sine and cosine functions as in paper "[Attention is what you need](https://arxiv.org/pdf/1706.03762.pdf)". Since position embedding is important, I think it's necessary to give a brief description how to implement it. In paper "[End-to-End Video Instance Segmentation with Transformers](https://arxiv.org/pdf/2011.14503.pdf)", it also used a transformer for segmentation, and gave a description how position info is embedded, while used experiments to demonstrate the effectiveness of pos embedding. So I think it may be better to give a briefly description of the implementation of pos embedding.

**Comment by lzrobots** [comment]
yes I clearly mentioned above that

 `we *learn* a specific position embedding`

**Comment by QiushiYang** [comment]
I have the same question.  Does "learn a specific position embedding" means using one linear (FC) layer mapping the original absolute coordinates inputs (with size: (L, 2)) to the size of (L, C) ?  Also, why use adding instead concatenation to fuse the position embedding and image embedding?

**Comment by lzrobots** [comment]
No. There is no such a thing (L, 2). We direct learn position embeddings with size (L, C).

**Comment by QiushiYang** [comment]
Thanks for your helps. Do you mean the position embeddings are also mapped by original patch-image: (L, 256)--(L,1024), just like the patch embedding, instead by the original coordinates of pixels? Will it be better to use absolute coordinates (L, 2) to map the position embedding?

**Comment by lzrobots** [comment]
there is no *mapping* in the position embedding. we directly learn the position embedding with size (L, C). You might need to take a quick tutorial on the transformer.

**Comment by 675492062** [comment]
> there is no _mapping_ in the position embedding. we directly learn the position embedding with size (L, C). You might need to take a quick tutorial on the transformer.

I have a question, the original image is divided into patches and the position encoding is based on these PATCHes, but what about the position encoding inside PATCHes? In this case, will there be any problem for dense prediction like semantic segmentation?
