### ISSUE TITLE
could please share the trained model（请问可以分享一下训练好的模型吗）

### ISSUE THREAD

**Issue by daixiaolei623** [fudan-zvg/SETR#22]
Thank you for your sharing.
because i only have one 1080 GPU, and it cannot trained your model(CUDA error: an illegal memory access was encountered), when i want to download your model, it shows 404 website, could you please share the trained model to my email: asertu@126.com
thank you very much.
同学你好，谢谢你的分享
但是由于我只有一块GPU因此无法训练你的模型，请问你可以把你训练好的模型分享到我的邮箱吗，谢谢。

**Comment by lzrobots** [comment]
Hi this is coming soon

**Comment by lzrobots** [comment]
uploaded
