### ISSUE TITLE
always CUDA out of memory

### ISSUE THREAD

**Issue by daixiaolei623** [fudan-zvg/SETR#24]
@lzrobots 
@VictorLlu 
@sixiaozheng 
Hi, thank you for your sharing.
however, when i run "./tools/dist_test.sh configs/SETR/SETR_PUP_512x512_160k_ade20k_bs_16_MS.py", i got the error: CUDA out of memory. I have 2 NVIDIA  Tesla P100 about 16GB per GPU.
Could you please tell me what is wrong.
Thank you.

**Comment by daixiaolei623** [comment]
could you please tell which GPU do you use and how big they are.

**Comment by lzrobots** [comment]
Hey have you ever run any segmentation model using 2*16G GPUs, eg, PSPNet, DeepLab V3 with ResNet101?

Please refer to #13

**Comment by GusRoth** [comment]
> @lzrobots
> @VictorLlu
> @sixiaozheng
> Hi, thank you for your sharing.
> however, when i run "./tools/dist_test.sh configs/SETR/SETR_PUP_512x512_160k_ade20k_bs_16_MS.py", i got the error: CUDA out of memory. I have 2 NVIDIA Tesla P100 about 16GB per GPU.
> Could you please tell me what is wrong.
> Thank you.

the authors have said that they used the 8x32g GPUs to run the SETR at zhihu
