### ISSUE TITLE
21k Pretrain weight

### ISSUE THREAD

**Issue by xiexinch** [fudan-zvg/SETR#28]
Could you please release the ResNet101 pretrained weights with ImageNet21K or tell us where can we find it? 
Thank you!

**Comment by lzrobots** [comment]
Hi I think the ViT paper does provide those weights.

**Comment by xiexinch** [comment]
Hi @lzrobots 
Sorry for bothering you, I have searched the official ViT repo, but I can't find the weights..
https://github.com/google-research/vision_transformer/issues/36
https://github.com/google-research/big_transfer/issues/21
Could you please provide a link?

**Comment by lzrobots** [comment]
you might get the weights from the readme file of the BiT repo you mentioned above.
