### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'group'

### ISSUE THREAD

**Issue by Frances1996** [fudan-zvg/SETR#29]
Hi, thanks for providing the code, When I use SETR_MLA_480x480_80k_pascal_context_bs_8.py and SETR_MLA_pascal_context_b8_80k.pth, I met this error:"AttributeError: module 'torch.distributed' has no attribute 'group'". How can I solve this on windows?
Below is my environment:
pytorch 1.6.0
mmcv 1.2.6
mmcv-full 1.1.5

**Comment by sixiaozheng** [comment]
Maybe your environment is installed incorrectly, please refer to the `A from-scratch setup script` in the `README.md` to reinstall the environment.
