### ISSUE TITLE
Question about Figure 8 in paper

### ISSUE THREAD

**Issue by wqhIris** [fudan-zvg/SETR#31]
Thank you for your nice work!
I am wondering how to get the attention map of the picked point, could you give a simple introduction?
![image](https://user-images.githubusercontent.com/33059293/122932315-360d4700-d3a0-11eb-8c14-f453b216ed8d.png)

**Comment by sixiaozheng** [comment]
You cna just take the certain row of the self-attention matrix `softmax(QK)` and get an `HWx1` matrix. Then reshaping it into `HxW` will be ok. For example, if you want to take the central pixel's attention map, you can choose the `(HW/2)`th row of the self-attention matrix `softmax(QK)`.

**Comment by wqhIris** [comment]
Got it, thank you very much!
