### ISSUE TITLE
Request for diverting flow to MMSegmentation.

### ISSUE THREAD

**Issue by MengzhangLI** [fudan-zvg/SETR#33]
Hi, congrats to acceptance of CVPR 2021.

I am the member of OpenMMLab and our vision is to provide abundant models in our codebase, where researchers could make fair and effective comparison in computer vision field easily, which could in turn make more citations of those original excellent works because of already built baselines.

As the first transformer model on semantic segmentation, SETR has gotten too much attention in related field.
That's why my colleagues re-implement SETR in MMSeg last several month. Please check our link: https://github.com/open-mmlab/mmsegmentation/tree/master/configs/setr.

So could you please add our link in your original github repositories? We hope more people could use this famous model. 

Lookig forward to your reply! Wish you make more great works in the future.

Best,

**Comment by lzrobots** [comment]
Hi many thanks for the efforts to reproduce SETR in mmseg. We did send official PR months ago and finally we are happy to see it lands on mmseg. Will add the link in our repo. We also see that the re-implementation performance is a little bit lower than ours so we'll take a look.
