### ISSUE TITLE
pascal_context dataset

### ISSUE THREAD

**Issue by ydhongHIT** [fudan-zvg/SETR#36]
https://github.com/fudan-zvg/SETR/blob/23f8fde88182c7965e91c28a0c59d9851af46858/configs/_base_/datasets/pascal_context.py#L30

There is no defination of 'dataset' in class Resize.

**Comment by sixiaozheng** [comment]
https://github.com/fudan-zvg/SETR/blob/23f8fde88182c7965e91c28a0c59d9851af46858/mmseg/datasets/pipelines/transforms.py#L9
