### ISSUE TITLE
 image size  doesn't match model 

### ISSUE THREAD

**Issue by mxmdpc** [fudan-zvg/SETR#39]
Hello:
when test pascal_context dataset, output:
AssertionError: Input image size (389*480) doesn't match model (480*480).

**Comment by sixiaozheng** [comment]
Yes, the input of pascal VOC dataset must be 480x480, please check again if the environment is installed correctly. Please refer to the `A from-scratch setup script` in the `README.md` to reinstall the environment. And run the command `./tools/dist_train.sh ${CONFIG_FILE} ${GPU_NUM}`.
