### ISSUE TITLE
Which checkpoint file is the best?

### ISSUE THREAD

**Issue by Kittywyk** [fudan-zvg/SETR#42]
Hi, thank you for your awesome work.

I trained SETR-MLA model on my own dataset, and there are many checkpoints files of different iterations. But how can I know which is the best one to test data? 

Thanks in advance.

**Comment by sixiaozheng** [comment]
You can choose a model with a larger mIoU to test your own dataset according to the mIoU results of each model in the README. However, it is recommended that you train the model on your own dataset to obtain better test set results with high probability.
