### ISSUE TITLE
mmcv error ,python3.7.0,pytorch 1.9.1，windows

### ISSUE THREAD

**Issue by cvJie** [fudan-zvg/SETR#46]
pip install mmcv
python setup.py develop
and run train.py

ImportError: DLL load failed: 找不到指定的模块。

can you give me some advices?
thanks

**Comment by sixiaozheng** [comment]
Maybe your environment is installed incorrectly, please refer to the A from-scratch setup script in the README.md to reinstall the environment. And run the command `./tools/dist_train.sh ${CONFIG_FILE} ${GPU_NUM}`.
